### ISSUE TITLE
Collaboration request.

### ISSUE THREAD

**Issue by Almas-Ali** [dhanoosu/TkTerm#2]
Hi, 
I am a creator of [Ant](https://github.com/Almas-Ali/Ant) interpreter. You can check it out. Here I have used Python basic shell and I wanted to add a GUI in this project. Suddenly while searching for a GUI project in Github I found your project. I want to know are you interested for a collaboration and make a complete shell type project. I am highly interested in this project. It will be a open source, free project for everyone who want to use or want to contribute.

Please checkout my project and let me know about your decision. I am waiting for your positive feedback.

Thank you for your precious time.

**Comment by dhanoosu** [comment]
Hey!

Sounds good. Can you elaborate more on the Ant interpreter? Does it interpret shell commands purely using python? Or a combination of python and subprocess calls to shell?

**Comment by Almas-Ali** [comment]
Sure! Basically [Ant](https://github.com/Almas-Ali/Ant) is a combination of custom builtin commands and operating system commands. OS commands are called using subprocess and custom commands are called as a python module. It has many features like custom path design (like: user@path > ), variable settings, path settings, custom commands support, aliases management, preloadable commands, preloadable aliases and lots more settings.

You can check the [README.md](https://github.com/Almas-Ali/Ant/blob/master/README.md) file for the full overview of this project. Currently, I am working on the core part to improve this project for vast use case. It can be package as a fully functional terminal application but without GUI it won't be so much attractive. So, I am asking you, would you like to contribute in this project. 

Let me know about your interest or not.

**Comment by dhanoosu** [comment]
Good. That is something that would be nice for my GUI to be integrated into. Looks like what you said would be possible. I will need to refactor my GUI into parts that handle front-end and back-end - that would allow me to slot in your codebase as a back-end and everything should work.

Let's take this up elsewhere.
Email me your contact details : dhanoo.surasarang@gmail.com
