### ISSUE TITLE
Folder change

### ISSUE THREAD

**Issue by LeonSnajdr** [dhanoosu/TkTerm#4]
If I start the terminal and type dir it prints out the current state of the folder I Executed it in:
![image](https://user-images.githubusercontent.com/94352142/232494775-a8e09230-a9c1-41fd-bd51-bb13b2488782.png)

If I now change the folder with "cd .." the result stays the same:
![image](https://user-images.githubusercontent.com/94352142/232495091-370267e8-d8ce-4b6a-be1c-9adf7adec5a2.png)

**Comment by dhanoosu** [comment]
Ah. I must have broken something while I refactored the repo. I'll push a fix by tonight. 😊

**Comment by dhanoosu** [comment]
This should be fixed now. Please do a pull.

**Comment by LeonSnajdr** [comment]
Very nice project btw.

**Comment by dhanoosu** [comment]
Thanks for checking out!
