### ISSUE TITLE
Trying to run gives me a tkinter event binding error

### ISSUE THREAD

**Issue by Moosems** [dhanoosu/TkTerm#6]
When I run the basic example given I get the following error on my Mac: `_tkinter.TclError: bad event type or keysym "ISO_Left_Tab"`

**Comment by dhanoosu** [comment]
Hi, can you pull and give it a try again. Thanks

**Comment by Moosems** [comment]
I'm using the pypi release :(.

**Comment by Moosems** [comment]
I modified the file on my local machine to get it working so now I can mess around with it.
